//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xwSearchLib.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class xwSearch : global::System.Configuration.ApplicationSettingsBase {
        
        private static xwSearch defaultInstance = ((xwSearch)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new xwSearch())));
        
        public static xwSearch Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Christopher\\Source\\Repos\\XWingAbilityFinder\\xwSearchLib\\Dictionary\\conv." +
            "data.verb")]
        public string VERB {
            get {
                return ((string)(this["VERB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Christopher\\Source\\Repos\\XWingAbilityFinder\\xwSearchLib\\Dictionary\\conv." +
            "data.noun")]
        public string NOUN {
            get {
                return ((string)(this["NOUN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Christopher\\Source\\Repos\\XWingAbilityFinder\\xwSearchLib\\Dictionary\\conv." +
            "data.adj")]
        public string ADVERB {
            get {
                return ((string)(this["ADVERB"]));
            }
        }
    }
}
